name: Lint 

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
      - uses: isort/isort-action@v0.1.0
      - uses: suo/flake8-github-action@v1
