name: Lint 

on:
  pull_request:
     paths: 
       - '*.py' 
  push:
    paths:
      - '*.py'
  

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
      - uses: isort/isort-action@v0.1.0
      - uses: suo/flake8-github-action@v1
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.4
          architecture: x64
      - name: Checkout Furcate
        uses: actions/checkout@v2
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8_py3'
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
